"""AI Mode: prompt strings for intent, SQL, chart, follow-up, summary, report."""

from ai_mode.prompts.prompt_ai_mode import (
    CHART_GENERATION_PROMPT,
    CONTEXT_REWRITE_PROMPT,
    FOLLOW_UP_DETECTION_PROMPT,
    INTENT_CLASSIFICATION_PROMPT,
    NO_DATA_HINT_PROMPT,
    REPORT_GENERATION_PROMPT,
    REPLY_TO_CLARIFICATION_AND_REWRITE_PROMPT,
    SQL_GENERATION_PROMPT,
    SPELLING_CORRECTION_PROMPT,
    SUMMARY_GENERATION_PROMPT,
)

__all__ = [
    "CHART_GENERATION_PROMPT",
    "CONTEXT_REWRITE_PROMPT",
    "FOLLOW_UP_DETECTION_PROMPT",
    "INTENT_CLASSIFICATION_PROMPT",
    "NO_DATA_HINT_PROMPT",
    "REPORT_GENERATION_PROMPT",
    "REPLY_TO_CLARIFICATION_AND_REWRITE_PROMPT",
    "SQL_GENERATION_PROMPT",
    "SPELLING_CORRECTION_PROMPT",
    "SUMMARY_GENERATION_PROMPT",
]
